### PR TITLE
Update QUICKSTART.md

### PR DESCRIPTION
**Pull request by markp3rry**
Made some edits based on experience of following this tutorial in v3.5.1 of Godot. I was able to complete the tutorial from start to finish, and end up with a working version of the sandbox with a deck containing the two custom cards that I could draw from.

### CODE REVIEW

**Comment by db0** [comment]
Question, does this still work on the latest 3.5.x? Why use 3.5.1?

**Comment by markp3rry** [comment]
> Question, does this still work on the latest 3.5.x? Why use 3.5.1?

Only reason is that it's the version I have on my laptop. I see that the latest LTS is 3.5.3 so if it's better to upgrade to that and test these changes again then happy to do that.

**Comment by db0** [comment]
yes please, just run a quick test if you can on the latest

**Comment by markp3rry** [comment]
> yes please, just run a quick test if you can on the latest

I have downloaded 3.5.3 and opened the project, compiled and run the deck builder without any issues.

**Comment by markp3rry** [comment]
I have updated the change to the quickstart.md to say 3.5.3 and not 3.5.1.

**Pull request merged**
